version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: ccard-postgres
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  payment-service:
    build:
      context: ./business/payment-service
    container_name: payment-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  postgres_data: